-- Puts back the three indexes the hunger/farm migration dropped by accident.
--
-- 20260917121716_hunger_meter_and_farm_plan was generated by `prisma migrate
-- dev` and kept the drops the diff proposes rather than declining them. All
-- three of these live only in raw migration SQL, so Prisma's schema cannot
-- express them and re-proposes dropping them on EVERY generated migration —
-- which is why at least eight earlier migrations here carry a header comment
-- recording that they were declined by hand. That one did not.
--
-- What it cost, if it ever runs:
--   ArchiveEntry_content_trgm_idx  — /archive and the transcript search
--   DirectMessage_content_trgm_idx — the DM desk's search (PLAYER-DESK.md)
--   Action_locationId_idx          — the per-Location Move lookups
-- The first two are trigram GIN indexes; without them those searches become
-- full-table scans on the two largest tables in the game, which is slow long
-- before it is obviously broken.
--
-- Written as a forward repair rather than by editing that migration, because
-- editing an APPLIED migration breaks Prisma's checksum for it and renaming
-- the directory does the same. IF NOT EXISTS on all three so this is correct
-- whether or not the bad migration has actually run anywhere yet.
--
-- Action.opposed is deliberately NOT restored. The column is a leftover of the
-- removed Opposed flag, nothing reads it, and master's schema.prisma has not
-- declared it for some time — dropping it was not that migration's business,
-- but it is not worth putting back either.

CREATE INDEX IF NOT EXISTS "ArchiveEntry_content_trgm_idx" ON "ArchiveEntry" USING GIN ("content" gin_trgm_ops);

CREATE INDEX IF NOT EXISTS "DirectMessage_content_trgm_idx" ON "DirectMessage" USING GIN ("content" gin_trgm_ops);

CREATE INDEX IF NOT EXISTS "Action_locationId_idx" ON "Action"("locationId");
